import React from "react";
import {
    View,
    Text,
    FlatList,
    TouchableOpacity,
    StyleSheet,
} from "react-native";

const missionsData = [
    // BASIC (10)
    {
        id: "b1",
        name: "Earth Recon Sweep",
        difficulty: "Basic",
        description: "Scan the area and eliminate minor Grineer presence.",
        faction: "Grineer",
        level: "1-5",
        reward: "Credits + Endo",
    },
    {
        id: "b2",
        name: "Supply Raid",
        difficulty: "Basic",
        description: "Retrieve stolen supplies from enemy camp.",
        faction: "Corpus",
        level: "2-6",
        reward: "Credits",
    },
    {
        id: "b3",
        name: "Infested Cleanup",
        difficulty: "Basic",
        description: "Clear low-level Infested outbreak.",
        faction: "Infested",
        level: "3-7",
        reward: "Mods",
    },
    {
        id: "b4",
        name: "Outpost Defense",
        difficulty: "Basic",
        description: "Defend a small base for 5 waves.",
        faction: "Grineer",
        level: "4-8",
        reward: "Endo",
    },
    {
        id: "b5",
        name: "Quick Capture",
        difficulty: "Basic",
        description: "Capture a fleeing target.",
        faction: "Corpus",
        level: "5-9",
        reward: "Credits",
    },
    {
        id: "b6",
        name: "Resource Hunt",
        difficulty: "Basic",
        description: "Collect resources across the map.",
        faction: "Infested",
        level: "2-6",
        reward: "Resources",
    },
    {
        id: "b7",
        name: "Recon Drone Escort",
        difficulty: "Basic",
        description: "Escort drone safely.",
        faction: "Grineer",
        level: "3-7",
        reward: "Credits",
    },
    {
        id: "b8",
        name: "Data Retrieval",
        difficulty: "Basic",
        description: "Hack terminal and extract data.",
        faction: "Corpus",
        level: "4-8",
        reward: "Mods",
    },
    {
        id: "b9",
        name: "Low Orbit Patrol",
        difficulty: "Basic",
        description: "Eliminate enemies in orbit station.",
        faction: "Grineer",
        level: "5-9",
        reward: "Credits",
    },
    {
        id: "b10",
        name: "Infested Nest Burn",
        difficulty: "Basic",
        description: "Destroy Infested nests.",
        faction: "Infested",
        level: "3-7",
        reward: "Endo",
    },

    // MODERATE (10)
    {
        id: "m1",
        name: "Corpus Vault Heist",
        difficulty: "Moderate",
        description: "Break into secure vault and extract data.",
        faction: "Corpus",
        level: "10-20",
        reward: "Rare Mods",
    },
    {
        id: "m2",
        name: "Grineer Stronghold",
        difficulty: "Moderate",
        description: "Assault fortified base.",
        faction: "Grineer",
        level: "12-22",
        reward: "Credits + Mods",
    },
    {
        id: "m3",
        name: "Infested Survival",
        difficulty: "Moderate",
        description: "Survive 10 minutes.",
        faction: "Infested",
        level: "15-25",
        reward: "Resources",
    },
    {
        id: "m4",
        name: "Mobile Defense",
        difficulty: "Moderate",
        description: "Protect 3 terminals.",
        faction: "Corpus",
        level: "14-24",
        reward: "Endo",
    },
    {
        id: "m5",
        name: "Sabotage Reactor",
        difficulty: "Moderate",
        description: "Destroy reactor core.",
        faction: "Grineer",
        level: "16-26",
        reward: "Credits",
    },
    {
        id: "m6",
        name: "Spy Operation",
        difficulty: "Moderate",
        description: "Hack 3 vaults undetected.",
        faction: "Corpus",
        level: "18-28",
        reward: "Rare Mods",
    },
    {
        id: "m7",
        name: "Defense Outpost",
        difficulty: "Moderate",
        description: "Defend for 10 waves.",
        faction: "Grineer",
        level: "12-22",
        reward: "Endo",
    },
    {
        id: "m8",
        name: "Infested Hive Hunt",
        difficulty: "Moderate",
        description: "Destroy 5 hives.",
        faction: "Infested",
        level: "15-25",
        reward: "Resources",
    },
    {
        id: "m9",
        name: "Capture Commander",
        difficulty: "Moderate",
        description: "Capture elite target.",
        faction: "Grineer",
        level: "17-27",
        reward: "Credits",
    },
    {
        id: "m10",
        name: "Supply Disruption",
        difficulty: "Moderate",
        description: "Disrupt enemy supply lines.",
        faction: "Corpus",
        level: "14-24",
        reward: "Mods",
    },

    // HARD (10)
    {
        id: "h1",
        name: "Elite Defense Grid",
        difficulty: "Hard",
        description: "Defend against elite waves.",
        faction: "Corpus",
        level: "30-40",
        reward: "Rare Mods",
    },
    {
        id: "h2",
        name: "Grineer War Zone",
        difficulty: "Hard",
        description: "Massive battlefield combat.",
        faction: "Grineer",
        level: "32-42",
        reward: "Credits",
    },
    {
        id: "h3",
        name: "Infested Nightmare",
        difficulty: "Hard",
        description: "High-density Infested survival.",
        faction: "Infested",
        level: "35-45",
        reward: "Resources",
    },
    {
        id: "h4",
        name: "High Risk Spy",
        difficulty: "Hard",
        description: "Advanced security vaults.",
        faction: "Corpus",
        level: "34-44",
        reward: "Rare Mods",
    },
    {
        id: "h5",
        name: "Boss Assassination",
        difficulty: "Hard",
        description: "Eliminate elite boss target.",
        faction: "Grineer",
        level: "36-46",
        reward: "Blueprints",
    },
    {
        id: "h6",
        name: "Endurance Defense",
        difficulty: "Hard",
        description: "Survive 15 waves.",
        faction: "Corpus",
        level: "30-40",
        reward: "Endo",
    },
    {
        id: "h7",
        name: "Dark Sector Raid",
        difficulty: "Hard",
        description: "Clear Infested territory.",
        faction: "Infested",
        level: "33-43",
        reward: "Resources",
    },
    {
        id: "h8",
        name: "Sabotage Facility",
        difficulty: "Hard",
        description: "Destroy heavily guarded facility.",
        faction: "Grineer",
        level: "31-41",
        reward: "Credits",
    },
    {
        id: "h9",
        name: "Elite Capture",
        difficulty: "Hard",
        description: "Capture elite operative.",
        faction: "Corpus",
        level: "35-45",
        reward: "Mods",
    },
    {
        id: "h10",
        name: "Tactical Defense",
        difficulty: "Hard",
        description: "Strategic defense mission.",
        faction: "Grineer",
        level: "32-42",
        reward: "Endo",
    },

    // ELITE (10)
    {
        id: "e1",
        name: "Void Anomaly",
        difficulty: "Elite",
        description: "Investigate dangerous void anomaly.",
        faction: "Corrupted",
        level: "50-60",
        reward: "Rare Rewards",
    },
    {
        id: "e2",
        name: "Elite Survival",
        difficulty: "Elite",
        description: "Survive 20 minutes.",
        faction: "Infested",
        level: "55-65",
        reward: "Resources",
    },
    {
        id: "e3",
        name: "Prime Defense",
        difficulty: "Elite",
        description: "Defend prime artifact.",
        faction: "Corpus",
        level: "52-62",
        reward: "Prime Parts",
    },
    {
        id: "e4",
        name: "Warframe Assassination",
        difficulty: "Elite",
        description: "Take down high-level boss.",
        faction: "Grineer",
        level: "58-68",
        reward: "Blueprints",
    },
    {
        id: "e5",
        name: "Elite Raid",
        difficulty: "Elite",
        description: "Multi-phase raid mission.",
        faction: "Corpus",
        level: "60-70",
        reward: "Rare Mods",
    },
    {
        id: "e6",
        name: "Void Defense",
        difficulty: "Elite",
        description: "Defend void structure.",
        faction: "Corrupted",
        level: "55-65",
        reward: "Prime Parts",
    },
    {
        id: "e7",
        name: "Nightmare Survival",
        difficulty: "Elite",
        description: "Extreme survival challenge.",
        faction: "Infested",
        level: "60-70",
        reward: "Resources",
    },
    {
        id: "e8",
        name: "Elite Sabotage",
        difficulty: "Elite",
        description: "Destroy elite facility.",
        faction: "Grineer",
        level: "57-67",
        reward: "Credits",
    },
    {
        id: "e9",
        name: "Omega Capture",
        difficulty: "Elite",
        description: "Capture top-tier target.",
        faction: "Corpus",
        level: "59-69",
        reward: "Mods",
    },
    {
        id: "e10",
        name: "Final Defense",
        difficulty: "Elite",
        description: "Ultimate defense challenge.",
        faction: "Corrupted",
        level: "65-75",
        reward: "Legendary Rewards",
    },
];

export default function MissionsScreen({ navigation }) {
    return (
        <FlatList
            data={missionsData}
            keyExtractor={(item) => item.id}
            renderItem={({ item }) => (
                <TouchableOpacity
                    onPress={() => navigation.navigate("Details", { item })}
                >
                    <View style={styles.card}>
                        <Text style={styles.title}>{item.name}</Text>
                        <Text style={styles.text}>Difficulty: {item.difficulty}</Text>
                        <Text style={styles.text}>Faction: {item.faction}</Text>
                        <Text style={styles.text}>Level: {item.level}</Text>
                    </View>
                </TouchableOpacity>
            )}
        />
    );
}

const styles = StyleSheet.create({
    card: {
        backgroundColor: "#1e1e1e",
        padding: 15,
        margin: 10,
        borderRadius: 10,
    },
    title: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
    },
    text: {
        color: "#ccc",
    },
});
